name: Linux Build Template

on:
  workflow_call:
    inputs:
      version:
        description: "Version number for the build"
        required: true
        type: string
      qt_version:
        description: "Qt version to use"
        required: false
        default: "6.11.2"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Version in code
        shell: pwsh
        env:
          VERSION: ${{ inputs.version }}
        run: |
          $version = (Get-Content -Path CMakeLists.txt -Raw) -replace 'VERSION 1.0', "VERSION `"$env:VERSION`""
          $version | Set-Content -Path CMakeLists.txt
          $version = (Get-Content -Path snapcraft.yaml -Raw) -replace 'version: 1.0.0', "version: `"$env:VERSION`""
          $version | Set-Content -Path snapcraft.yaml
          $version = (Get-Content -Path src/main.cpp -Raw) -replace 'constexpr auto Version = "1.0.0";', "constexpr auto Version = `"$env:VERSION`";"
          $version | Set-Content -Path src/main.cpp
          cat src/main.cpp

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ inputs.qt_version }}

      - name: CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./linux .
          cmake --build . --config Release --parallel 32
          cmake --install .

      - name: CPack
        run: |
          cpack -G 7Z
          cpack -G ZIP
          cpack -G TBZ2
          cpack -G TGZ
          cpack -G TXZ
          cpack -G TZ
          cpack -G DEB
          cpack -G RPM

      #- name: Snapcraft
      #  run: |
      #    sudo snap install snapcraft --classic
      #    snapcraft
      #  env:
      #    SNAPCRAFT_BUILD_ENVIRONMENT: host

      - name: Publish Zip archive
        uses: actions/upload-artifact@v4
        with:
          name: Linux_Binary_v${{ inputs.version }}
          path: |
            SQLQueryAnalyzer-${{ inputs.version }}-Linux.zip

      - name: Publish Debian package
        uses: actions/upload-artifact@v4
        with:
          name: Debian_Package_v${{ inputs.version }}
          path: |
            SQLQueryAnalyzer-${{ inputs.version }}-Linux.deb

      - name: Publish RPM package
        uses: actions/upload-artifact@v4
        with:
          name: RPM_Package_v${{ inputs.version }}
          path: |
            SQLQueryAnalyzer-${{ inputs.version }}-Linux.rpm

    #- name: Publish Snap package
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: Snap_v${{ inputs.version }}
    #    path: |
    #      *.snap
