name: Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/linux*.yml'
      - '!**/*.cpp'
      - '!**/*.h'
      - '!**/*.ui'
      - '!CMakeLists.txt'
      - '!src/**/*'
    branches:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/linux-template.yml
    with:
      version: '0.3.${{ github.run_number }}'