name: Build MacOS Template

on:
  workflow_call:
    inputs:
      version:
        description: "Version number for the build"
        required: true
        type: string
      os:
        description: build agent
        required: true
        type: string
      architecture:
        description: cpu architecture
        required: true
        type: string

jobs:
  template:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Update Version in code
        shell: pwsh
        env:
          VERSION: ${{ inputs.version }}
        run: |
          $version = (Get-Content -Path CMakeLists.txt -Raw) -replace 'VERSION 1.0', "VERSION `"$env:VERSION`""
          $version | Set-Content -Path CMakeLists.txt
          $version = (Get-Content -Path src/main.cpp -Raw) -replace 'constexpr auto Version = "1.0.0";', "constexpr auto Version = `"$env:VERSION`";"
          $version | Set-Content -Path src/main.cpp

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.11.2"

      - name: CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install .
          cmake --build . --config Release --parallel 32
          cmake --install .

      - name: macdeployqt
        run: macdeployqt install/SQLQueryAnalyzer.app -dmg -appstore-compliant

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SQLQueryAnalyzer_MacOS_v${{ inputs.version }}_${{ inputs.architecture }}
          path: |
            install/SQLQueryAnalyzer.dmg
