name: MacOS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - "!.github/workflows/macos*.yml"
      - "!**/*.cpp"
      - "!**/*.h"
      - "!**/*.ui"
      - "!CMakeLists.txt"
      - "!src/**/*"
    branches:
      - "**"

jobs:
  macos-arm64:
    uses: ./.github/workflows/macos-template.yml
    with:
      version: "0.3.${{ github.run_number }}"
      os: "macos-latest"
      architecture: "arm64"

  macos-intel:
    uses: ./.github/workflows/macos-template.yml
    with:
      version: "0.3.${{ github.run_number }}"
      os: "macos-15"
      architecture: "intel"
