name: Windows

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/windows*.yml'
      - '!**/*.cpp'
      - '!**/*.h'
      - '!**/*.ui'
      - '!CMakeLists.txt'
      - '!src/**/*'
      - '!deps/postgresql/**'
    branches:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/windows-template.yml
    with:
      version: 0.3.${{ github.run_number }}
      release: false
    secrets: inherit
